- hosts: "localhost"
  tasks:
    - name: "Use role-a to set vars"
      include_role:
        name: role-a

    - name: "Add an apt repository"
      # apt_repo is unresolved module --> ARI detects unresolved module
      community.general.apt_repo:
        repo: "sample-repo"
        state: present
      vars:
        var2: "task_vars_value2"
        var4: "task_vars_value4"

    - name: "Install package"
      ansible.builtin.apt:
        # these variables are undefined --> ARI detects undefined vars
        name: "something:1.2.3"
        state: present

    - name: "Configure firewall"
      community.general.ufw:
        state: present